# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 22:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=3)),
                ('candidate_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid mobile number', regex='^\\+?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('work_exp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('analytics_exp', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('current_loc', models.CharField(max_length=100)),
                ('corrected_city', models.CharField(max_length=50)),
                ('nearest_city', models.CharField(max_length=50)),
                ('preffered_loc', models.CharField(max_length=100)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_employer', models.CharField(blank=True, max_length=50)),
                ('current_designation', models.CharField(blank=True, max_length=50)),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('ug_course', models.CharField(blank=True, max_length=30)),
                ('ug_institute_name', models.CharField(blank=True, max_length=50)),
                ('ug_passing_year', models.PositiveSmallIntegerField(blank=True)),
                ('ug_tire1', models.CharField(blank=True, max_length=3)),
                ('pg_course', models.CharField(blank=True, max_length=30)),
                ('current_pg_course', models.CharField(blank=True, max_length=30)),
                ('pg_institute_name', models.CharField(blank=True, max_length=50)),
                ('pg_tire1', models.CharField(blank=True, max_length=3)),
                ('pg_passing_year', models.PositiveSmallIntegerField(blank=True)),
                ('post_pg_course', models.CharField(blank=True, max_length=30)),
                ('current_post_pg_course', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
