# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='pg_passing_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ug_passing_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
