# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 14:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20161228_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='analytics_exp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ctc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='work_exp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
