# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_auto_20161230_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='pg_tire1',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ug_tire1',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
